### ISSUE TITLE
Loading complex types seems to be broken with the latest HDF5_jll release

### ISSUE THREAD

**Issue by rgaudette** [JuliaIO/JLD.jl#281]
With the latest HDF5_jll release it seems that loading JLD files is broken.  I can successfully run the example described in the **Types and their definitions** section. But, if I make the example a little more complex by adding a sparse matrix to the example, I am not able to load the data I have just written.  To be more specific, if I define MyTypes as:
```
module MyTypes
export MyType
using SparseArrays
struct MyType
    value::Int
    s_array::SparseMatrixCSC
end
end
```

create a an instance of a MyType with
```
using SparseArrays
using MyTypes
x = MyType(3, spdiagm(-1 => [1,2,3,4], 1 => [4,3,2,1]))
```

saving the instance with

```
jldopen("somedata.jld", "w") do file
    addrequire(file, MyTypes)
    write(file, "x", x)
end
```

appears work fine.  

But when trying to load it back in with
`d = JLD.load("somedata.jld")`
I receive the following error:
```
ERROR: stored type MyTypes.MyType does not match currently loaded type
Stacktrace:
 [1] jldatatype(::JLD.JldFile, ::HDF5.HDF5Datatype) at C:\Users\rick\.julia\packages\JLD\jeGJb\src\jld_types.jl:723
 [2] read(::JLD.JldDataset) at C:\Users\rick\.julia\packages\JLD\jeGJb\src\JLD.jl:367
 [3] read(::JLD.JldFile, ::String) at C:\Users\rick\.julia\packages\JLD\jeGJb\src\JLD.jl:343
 [4] #43 at .\none:0 [inlined]
 [5] iterate at .\generator.jl:47 [inlined]
 [6] collect_to!(::Array{Tuple{String,Integer},1}, ::Base.Generator{Array{String,1},JLD.var"#43#45"{JLD.JldFile}}, ::Int64, ::Int64) at .\array.jl:732
 [7] collect_to!(::Array{Tuple{String,UInt32},1}, ::Base.Generator{Array{String,1},JLD.var"#43#45"{JLD.JldFile}}, ::Int64, ::Int64) at .\array.jl:740
 [8] collect_to_with_first!(::Array{Tuple{String,UInt32},1}, ::Tuple{String,UInt32}, ::Base.Generator{Array{String,1},JLD.var"#43#45"{JLD.JldFile}}, ::Int64) at .\array.jl:710
 [9] collect(::Base.Generator{Array{String,1},JLD.var"#43#45"{JLD.JldFile}}) at .\array.jl:691
 [10] (::JLD.var"#42#44")(::JLD.JldFile) at C:\Users\rick\.julia\packages\JLD\jeGJb\src\JLD.jl:1246
 [11] jldopen(::JLD.var"#42#44", ::String, ::Vararg{String,N} where N; kws::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at C:\Users\rick\.julia\packages\JLD\jeGJb\src\JLD.jl:243
 [12] jldopen(::Function, ::String, ::String) at C:\Users\rick\.julia\packages\JLD\jeGJb\src\JLD.jl:241
 [13] load(::FileIO.File{FileIO.DataFormat{:JLD}}) at C:\Users\rick\.julia\packages\JLD\jeGJb\src\JLD.jl:1245
 [14] load(::String; options::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at C:\Users\rick\.julia\packages\FileIO\2fEu2\src\loadsave.jl:136
 [15] load(::String) at C:\Users\rick\.julia\packages\FileIO\2fEu2\src\loadsave.jl:136
 [16] top-level scope at REPL[10]:1
```

I also tried adding a `addrequire(file, SparseArrays)` to the do block and that produced the same error.

**Comment by jacobcook1995** [comment]
+1 I have been getting an identical error. When I revert to the previous version of HDF5_jll the error stops occurring. When I do this data that was written out with the new version of HDF5_jll can be correctly read in, which might suggest the problem is at the reading rather than writing stage

**Comment by szafna** [comment]
+1
 [0234f1f7] + HDF5_jll v1.12.0+0
Julia 1.5.3
same error on Windows and Linux
MWE
```julia
using JLD
Base.@kwdef mutable struct profile9
    end_node::Array{Int32,2} = [0 0 0]
	
end

save("p9.jld","prf",profile9())
load("p9.jld")
```
```julia
ERROR: stored type profile9 does not match currently loaded type
```

**Comment by szafna** [comment]
> +1 I have been getting an identical error. When I revert to the previous version of HDF5_jll the error stops occurring. When I do this data that was written out with the new version of HDF5_jll can be correctly read in, which might suggest the problem is at the reading rather than writing stage

Is there a way to install previous version of HDF5_jll?

**Comment by jmert** [comment]
I think this is a compatibility bounding error in HDF5.jl v0.13.6 which should stick with the HDF5_jll v1.10 libraries — only the new HDF5.jl v0.14 should be using HDF5_jll v1.12. (JLD right now is version bounded on HDF5.jl v0.13 series.)

**Comment by jacobcook1995** [comment]
> > +1 I have been getting an identical error. When I revert to the previous version of HDF5_jll the error stops occurring. When I do this data that was written out with the new version of HDF5_jll can be correctly read in, which might suggest the problem is at the reading rather than writing stage
> 
> Is there a way to install previous version of HDF5_jll?

In the julia package manager I just wrote:
`add HDF5_jll@1.10`
which pins the HDF5_jll package to v1.10.5+7 (the intermediate versions don't seem to exist for some reason)

**Comment by musm** [comment]
This should now be fixed thanks to @jmert  fixing the compat bounds on HDF5.jl 
https://github.com/JuliaRegistries/General/pull/24885#issuecomment-729816318

**Comment by GregPlowman** [comment]
I'm still getting this error.
After Pkg.update() I have this in my environment:
```
JLD v0.10.0
HDF5 v0.13.6
HDF5_jll v1.12.0+0
```
Which packages(s) do I need to downgrade?

**Comment by jmert** [comment]
HDF5_jll needs to be downgraded back to v1.10.5, but that should be imposed if you update HDF5 to v0.13.7.

**Comment by GregPlowman** [comment]
Thanks, that worked!
Seems resolver preferenced higher `HDF5_jll` rather than higher `HDF5`.
So required manually upgrading `HDF5`.

**Comment by musm** [comment]
Hmm wouldn't the resolver pick out the  highest compatible HDF5 version which should be the latest tagged version which would then downgrade HDF5_jll?

**Comment by musm** [comment]
I'm also curious what exactly is incompatible in the newer hdf5 library version. The errors here don't seem to indicate what's going on to trigger it.  This might be easier to see using jmert's upgraded branch.

**Comment by oskarddfa** [comment]
This can also be solved by uncommenting lines 723-725 of jld_types.jl
I.e. 
```
# if T !== Expr  # in julia >= 0.7 Expr has 1 fewer fields; the trailing field can be ignored.
#     dtype == newtype || throw(TypeMismatchException(typename))
# end
```
Trying to print out `dtype` and `newtype` returns the same and loading the data still works. 
Don't know why, just wanted to add that info.
